const ImagePath = {
    familyIcon: require('../assets/loginfamilyicon.png'),
    facebookIcon:require('../assets/facebookIcon.png'),
    googleIcon:require('../assets/googleIcon.png'),
    twitterIcon:require('../assets/twittericon.png'),
    plusIcon:require('../assets/plusicon.png'),
    JohnDoe:require('../assets/johndea.png'),
    Notification:require('../assets/notification.png'),
    ProfileComplete:require('../assets/profilecompleteheck.png'),
    WelcomeDesign:require('../assets/welcomedesign.png'),
    WelcomeText:require('../assets/welcometext.png'),
    HomeScreenTab:require('../assets/hometab.png'),
    Habittab:require('../assets/habits.png'),
    KidsProfiletab:require('../assets/kidsprofile.png'),
    Achievementtab:require('../assets/Achievement.png'),
    Selfprofiletab:require('../assets/selfprofile.png'),
    HomeGirl:require('../assets/homegirl.png'),
    Swimming:require('../assets/swimming.png'),
    Wakeup:require('../assets/wakeup.png'),
    wakeupOne:require('../assets/walkupone.png'),
    Reading:require('../assets/reading.png'),
    Eating:require('../assets/eating.png'),
    Homeuser:require('../assets/homeuser.png'),
    Homelike:require('../assets/homelike.png'),
    ThreeOne:require('../assets/threedots.png'),
    Routine:require('../assets/routine.png'),
    Rewards:require('../assets/rewards.png'),
    Routing:require('../assets/onboardingrouting.png'),
    ProfileLogo:require('../assets/profilelogo.png'),
    Camera:require('../assets/camera.png'),
    Alertok:require('../assets/alerttik.png'),
    AlertCancel:require('../assets/alertcancel.png'),
    Alertgirl:require('../assets/alertgirl.png'),
    AlertChild:require('../assets/Alertchild.png'),
    Gift:require('../assets/gift.png'),
    Edit:require('../assets/edit.png'),
    Cyclegift:require('../assets/cyclegift.png'),
    Bookgift:require('../assets/bookgift.png'),
  };
  
  export default ImagePath;