const ImagePath = {
    logo: require('../assets/logo.png'),
    Welcome: require('../assets/welcome1.png'),
    WelcomeRound: require('../assets/Welcome_round.png'),
    WelecomeLine: require('../assets/Rectangle1.png'),
    WelecomeLine2: require('../assets/Rectangle2.png'),
    Sir: require('../assets/sir.png'),
    BackGround: require('../assets/bg.png'),
    Msg: require('../assets/msg.png'),
    Facebook: require('../assets/fb.png'),
    Google: require('../assets/google.png'),
    Apple: require('../assets/apple.png'),
    Password: require('../assets/Password.png'),
    Closedeye: require('../assets/closedeye.png'),
    Smalllogo: require('../assets/smalllogo.png'),
    SearchIcon: require('../assets/searchicon.png'),
    Home: require('../assets/Home.png'),
    Course: require('../assets/courses.png'),
    Wishlist: require('../assets/wishlist.png'),
    Account: require('../assets/Account.png'),
    PhpTraining: require('../assets/phptraining.png'),
    Book: require('../assets/book.png'),
    Start: require('../assets/star.png'),
    User: require('../assets/User.png'),
    Pencil: require('../assets/pencil.png'),
    Arrow: require('../assets/arrow.png'),
    RedLike: require('../assets/redheart.png'),
    backButton: require('../assets/Drawback.png'),
    SmallClip: require('../assets/Smalclip.png'),
    SmallSlab: require('../assets/Slabsmall.png'),
    LongSlab: require('../assets/slablong.png'),
    WhiteSlab: require('../assets/whiteslab.png'),
    WhiteSmallSlab: require('../assets/smallwhiteslab.png'),
    clip: require('../assets/clip.png'),
    ReactangeVideo: require('../assets/RectangeVideo.png'),
    unLike: require('../assets/unLike.png'),
    back: require('../assets/back.png'),
    Drop:require('../assets/drop.png'),
  };
  
  export default ImagePath;